[pytest]
pythonpath = src
addopts = --ignore=venv --ignore=.venv
markers = 
	slow: marks tests as slow (deselect with '-m "not slow"')
filterwarnings =
    # Ignore warnings from dependencies that are out of our control
    ignore:Use 'content=<...>' to upload raw bytes/text content.:DeprecationWarning
    ignore:Pydantic serializer warnings:UserWarning
