"""
LLM-compiled training loop combining atomic features: grad_accum, elem_grad_clip, validation
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'elem_grad_clip', 'validation']
__llm_compiled__ = True

from typing import Optional, Dict, Any, List
import torch
import torch.nn as nn
from torch.nn.utils import clip_grad_value_


@torch.no_grad()
def _eval_loss(model: nn.Module, loss_fn, loader) -> float:
    """Helper to compute validation loss."""
    was_training = model.training
    model.eval()
    total, count = 0.0, 0
    for batch in loader:
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total += float(loss.detach().cpu().item())
        count += 1
    if was_training:
        model.train()
    return total / max(count, 1)


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    accum_steps: int = 1,
    elem_grad_clip: Optional[float] = None,
    val_loader = None,
    val_interval: int = 10,
    **kwargs,
) -> Dict[str, Any]:
    """Training loop combining gradient accumulation, elementwise gradient clipping, and validation."""
    model.train()

    if accum_steps < 1:
        accum_steps = 1

    val_loss_history: List[float] = []
    micro_idx = 0
    optimizer.zero_grad(set_to_none=True)

    for batch_idx, batch in enumerate(train_loader):
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)

        if accum_steps > 1:
            loss = loss / float(accum_steps)

        loss.backward()
        micro_idx += 1

        if micro_idx % accum_steps == 0:
            if elem_grad_clip is not None:
                params = [p for p in model.parameters() if p.grad is not None]
                if params:
                    clip_grad_value_(params, elem_grad_clip)

            optimizer.step()
            optimizer.zero_grad(set_to_none=True)

        if val_loader is not None and (batch_idx % val_interval == 0 or batch_idx == len(train_loader) - 1):
            val_loss = _eval_loss(model, loss_fn, val_loader)
            val_loss_history.append(val_loss)

    # Handle case where last accumulation window is incomplete
    if micro_idx % accum_steps != 0:
        if elem_grad_clip is not None:
            params = [p for p in model.parameters() if p.grad is not None]
            if params:
                clip_grad_value_(params, elem_grad_clip)
        optimizer.step()

    result = {"model": model}
    if val_loader is not None:
        result["val_loss_history"] = val_loss_history

    return result