"""
LLM-compiled training loop combining atomic features: grad_accum, elem_grad_clip, loss_tracking
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'elem_grad_clip', 'loss_tracking']
__llm_compiled__ = True

import torch
import torch.nn as nn
from torch.nn.utils import clip_grad_value_
from typing import Optional, Dict, Any, List

def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # grad accum knobs
    accum_steps: int = 1,
    # elementwise grad clipping knobs
    elem_grad_clip: Optional[float] = None,
    # loss tracking knobs
    track_loss: bool = True,
    log_interval: int = 1,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Training loop combining gradient accumulation, elementwise gradient clipping, and loss tracking."""
    model.train()
    
    if accum_steps is None or accum_steps < 1:
        accum_steps = 1
    
    train_loss_history: List[float] = []
    micro_idx = 0
    optimizer.zero_grad(set_to_none=True)
    
    for batch_idx, batch in enumerate(train_loader):
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)
        
        if accum_steps > 1:
            loss = loss / float(accum_steps)
        
        loss.backward()
        micro_idx += 1
        
        if micro_idx % accum_steps == 0:
            if elem_grad_clip is not None:
                params = [p for p in model.parameters() if p.grad is not None]
                if params:
                    clip_grad_value_(params, elem_grad_clip)
            
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)
        
        # Track loss if enabled
        if track_loss and (batch_idx % log_interval == 0):
            train_loss_history.append(float(loss.detach().cpu().item()) * (accum_steps if accum_steps > 1 else 1))
    
    # Handle case where last accumulation window is incomplete
    if micro_idx % accum_steps != 0:
        if elem_grad_clip is not None:
            params = [p for p in model.parameters() if p.grad is not None]
            if params:
                clip_grad_value_(params, elem_grad_clip)
        optimizer.step()
    
    result = {"model": model}
    if track_loss:
        result["train_loss_history"] = train_loss_history
    
    return result