"""
LLM-compiled training loop combining atomic features: grad_accum, grad_norm_clip, loss_tracking, step_limiting, validation, mixed_precision, multi_epoch, lr_scheduling
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'grad_norm_clip', 'loss_tracking', 'step_limiting', 'validation', 'mixed_precision', 'multi_epoch', 'lr_scheduling']
__llm_compiled__ = True

from typing import Optional, Dict, Any, List
import torch
import torch.nn as nn
from torch.nn.utils import clip_grad_norm_
from torch.cuda.amp import GradScaler, autocast
from utils.device import best_device as device

@torch.no_grad()
def _eval_loss(model: nn.Module, loss_fn, loader) -> float:
    was_training = model.training
    model.eval()
    total, count = 0.0, 0
    for batch in loader:
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total += float(loss.detach().cpu().item())
        count += 1
    if was_training:
        model.train()
    return total / max(count, 1)

def _is_amp_compatible(device_str: str) -> bool:
    if device_str.startswith('cuda'):
        return True
    elif device_str == 'mps':
        return False
    return False

def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    accum_steps: int = 1,
    norm_clip_value: Optional[float] = 1.0,
    track_loss: bool = True,
    log_interval: int = 1,
    max_steps: Optional[int] = None,
    val_loader = None,
    val_interval: int = 10,
    use_amp: Optional[bool] = None,
    num_epochs: int = 1,
    lr_scheduler_type: str = "cosine",
    warmup_steps: int = 0,
    max_lr: Optional[float] = None,
    min_lr: float = 0.0,
    total_steps: Optional[int] = None,
    device: str = device,
    **kwargs,
) -> Dict[str, Any]:
    model.train()
    
    if accum_steps < 1:
        accum_steps = 1
    
    if use_amp is None:
        use_amp = _is_amp_compatible(device)
    
    if use_amp and not _is_amp_compatible(device):
        print(f"Warning: AMP requested but not compatible with {device}. Falling back to FP32.")
        use_amp = False
    
    scaler = GradScaler() if use_amp else None
    
    if total_steps is None:
        total_steps = len(train_loader) * num_epochs
    
    if max_lr is None:
        max_lr = optimizer.param_groups[0]['lr']
    
    scheduler = None
    if lr_scheduler_type == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=total_steps, eta_min=min_lr)
    elif lr_scheduler_type == "linear":
        def lambda_lr(step):
            if step < warmup_steps:
                return step / max(1, warmup_steps)
            progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
            return max(min_lr / max_lr, 1.0 - progress)
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lambda_lr)
    elif lr_scheduler_type == "step":
        step_size = max(1, total_steps // 3)
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=0.1)
    elif lr_scheduler_type == "exponential":
        gamma = (min_lr / max_lr) ** (1.0 / total_steps)
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=gamma)
    
    train_loss_history: List[float] = []
    val_loss_history: List[float] = []
    
    step_count = 0
    micro_idx = 0
    optimizer.zero_grad(set_to_none=True)
    
    for epoch in range(num_epochs):
        for batch_idx, batch in enumerate(train_loader):
            if max_steps is not None and step_count >= max_steps:
                break
            
            xb, yb = batch
            
            if use_amp:
                with autocast(device_type=device):
                    logits = model(xb)
                    loss = loss_fn(logits, yb)
            else:
                logits = model(xb)
                loss = loss_fn(logits, yb)
            
            if accum_steps > 1:
                loss = loss / float(accum_steps)
            
            if use_amp:
                scaler.scale(loss).backward()
            else:
                loss.backward()
            
            micro_idx += 1
            
            if micro_idx % accum_steps == 0:
                if norm_clip_value is not None:
                    if use_amp:
                        scaler.unscale_(optimizer)
                    clip_grad_norm_(model.parameters(), norm_clip_value)
                
                if use_amp:
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    optimizer.step()
                
                optimizer.zero_grad(set_to_none=True)
                
                if scheduler is not None:
                    scheduler.step()
                
                step_count += 1
            
            if track_loss and (batch_idx % log_interval == 0):
                train_loss_history.append(float(loss.detach().cpu().item()))
            
            if val_loader is not None and (batch_idx % val_interval == 0 or batch_idx == len(train_loader) - 1):
                val_loss = _eval_loss(model, loss_fn, val_loader)
                val_loss_history.append(val_loss)
    
    if micro_idx % accum_steps != 0:
        if norm_clip_value is not None:
            if use_amp:
                scaler.unscale_(optimizer)
            clip_grad_norm_(model.parameters(), norm_clip_value)
        
        if use_amp:
            scaler.step(optimizer)
            scaler.update()
        else:
            optimizer.step()
    
    result = {"model": model}
    if track_loss:
        result["train_loss_history"] = train_loss_history
    if val_loader is not None:
        result["val_loss_history"] = val_loss_history
    
    return result
