"""
LLM-compiled training loop combining atomic features: checkpoint_over_steps, logging, lr_scheduling
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['checkpoint_over_steps', 'logging', 'lr_scheduling']
__llm_compiled__ = True

from typing import Optional, Dict, Any
import os
import torch
import torch.nn as nn
from gpt_lab.logger import ExperimentLogger
import gpt_lab.checkpointer as checkpointer

def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # checkpoint_over_steps
    save_every_steps: Optional[int] = None,
    output_dir: Optional[str] = None,
    # logging
    logger: Optional[ExperimentLogger] = None,
    # lr_scheduling
    lr_scheduler_type: Optional[str] = None,
    scheduler_kwargs: Optional[Dict[str, Any]] = None,
    warmup_steps: int = 0,
    max_lr: Optional[float] = None,
    min_lr: float = 0.0,
    total_steps: Optional[int] = None,
    **kwargs
) -> Dict[str, Any]:
    model.train()
    optimizer.zero_grad(set_to_none=True)

    if total_steps is None:
        try:
            total_steps = len(train_loader)
        except:
            total_steps = 1000

    if max_lr is None:
        max_lr = optimizer.param_groups[0]['lr']

    scheduler = None
    scheduler_kwargs = scheduler_kwargs or {}
    if lr_scheduler_type == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=total_steps, eta_min=min_lr, **scheduler_kwargs
        )
    elif lr_scheduler_type == "linear":
        def lambda_lr(step):
            if step < warmup_steps:
                return step / max(1, warmup_steps)
            progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
            return max(min_lr / max_lr, 1.0 - progress)
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lambda_lr, **scheduler_kwargs)
    elif lr_scheduler_type == "step":
        step_size = max(1, total_steps // 3)
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=0.1, **scheduler_kwargs)
    elif lr_scheduler_type == "exponential":
        gamma = (min_lr / max_lr) ** (1.0 / total_steps)
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=gamma, **scheduler_kwargs)
    elif lr_scheduler_type == "lambda_lr":
        if "lr_lambda" not in scheduler_kwargs:
            raise ValueError("`scheduler_kwargs` must contain `lr_lambda` function for `lambda_lr` scheduler.")
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, **scheduler_kwargs)

    step_count = 0
    for batch in train_loader:
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)

        if logger:
            logger.log({"train_loss": loss.item()})
            if scheduler:
                logger.log({"learning_rate": scheduler.get_last_lr()[0]})

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        step_count += 1

        if (save_every_steps is not None 
            and output_dir is not None
            and step_count > 0 
            and step_count % save_every_steps == 0):
                raw_model = model.module if hasattr(model, 'module') else model
                checkpointer.save_checkpoint(
                    save_dir=os.path.join(output_dir, "checkpoints"),
                    filename=f"step_{step_count}.pt",
                    metadata={"step": step_count, "config": kwargs.get("config", {})},
                    model=raw_model,
                    optimizer=optimizer,
                    scheduler=scheduler
                )
                if logger:
                    logger.log({"checkpoint_saved": step_count})

    return {"model": model}
