"""
LLM-compiled training loop combining atomic features: checkpoint_best_model, checkpoint_over_steps, device, grad_accum, grad_norm_clip, logging, loss_tracking, lr_scheduling, mixed_precision, step_limiting, tqdm, validation
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['checkpoint_best_model', 'checkpoint_over_steps', 'device', 'grad_accum', 'grad_norm_clip', 'logging', 'loss_tracking', 'lr_scheduling', 'mixed_precision', 'step_limiting', 'tqdm', 'validation']
__llm_compiled__ = True

from typing import Optional, Dict, Any, List
import os
import logging

import torch
import torch.nn as nn
from torch.nn.utils import clip_grad_norm_
from torch.utils.data import IterableDataset
from tqdm.auto import tqdm as tqdm_auto

import gpt_lab.checkpointer as checkpointer
from gpt_lab.device import to_device

logger = logging.getLogger(__name__)


@torch.no_grad()
def _eval_loss(model: nn.Module, loader, device: str) -> float:
    """Helper to compute validation loss."""
    was_training = model.training
    model.eval()
    total, count = 0.0, 0
    for batch in loader:
        batch = to_device(batch, device)
        loss = model(batch)
        total += float(loss.detach().cpu().item())
        count += 1
    if was_training:
        model.train()
    return total / max(count, 1)


def _is_amp_compatible(device_str: str) -> bool:
    """Check if device supports AMP properly."""
    if device_str.startswith('cuda'):
        return True
    elif device_str == 'mps':
        return False
    return False


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    train_loader,
    *,
    # device knobs
    device: Optional[str] = None,
    # grad accum knobs
    accum_steps: int = 1,
    # grad norm clipping knobs
    norm_clip_value: Optional[float] = None,
    # logging
    enable_logging: bool = False,
    # loss tracking knobs
    track_loss: bool = False,
    log_interval: int = 1,
    # learning rate scheduling knobs
    lr_scheduler_type: Optional[str] = None,
    scheduler_kwargs: Optional[Dict[str, Any]] = None,
    warmup_steps: int = 0,
    max_lr: Optional[float] = None,
    min_lr: float = 0.0,
    # mixed precision knobs
    use_amp: bool = False,
    loss_scale: Optional[float] = None,
    # step limiting knobs
    total_steps: Optional[int] = None,
    # tqdm knobs
    use_tqdm: bool = False,
    # validation knobs
    val_loader = None,
    val_interval: int = 10,
    # checkpoint_best_model knobs
    save_best_model: bool = False,
    # checkpoint_over_steps knobs
    save_every_steps: Optional[int] = None,
    output_dir: Optional[str] = None,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Combined training loop with all atomic features."""
    
    # Determine target device
    if device is None:
        device = str(next(model.parameters()).device)
    
    # Move model to device
    model = model.to(device)
    model.train()
    
    # Handle gradient accumulation
    if accum_steps is None or accum_steps < 1:
        accum_steps = 1
    
    # Determine total steps for scheduling and progress bar
    if total_steps is None:
        try:
            total_steps = len(train_loader) // accum_steps
        except:
            total_steps = 1000  # fallback
    
    # Get current learning rate for max_lr if not specified
    if max_lr is None:
        max_lr = optimizer.param_groups[0]['lr']
    
    # Create scheduler
    scheduler = None
    scheduler_kwargs = scheduler_kwargs or {}
    if lr_scheduler_type == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=total_steps, eta_min=min_lr, **scheduler_kwargs
        )
    elif lr_scheduler_type == "linear":
        def lambda_lr(step):
            if step < warmup_steps:
                return step / max(1, warmup_steps)
            progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
            return max(min_lr / max_lr, 1.0 - progress)
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lambda_lr, **scheduler_kwargs)
    elif lr_scheduler_type == "step":
        step_size = max(1, total_steps // 3)
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=0.1, **scheduler_kwargs)
    elif lr_scheduler_type == "exponential":
        gamma = (min_lr / max_lr) ** (1.0 / total_steps)
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=gamma, **scheduler_kwargs)
    elif lr_scheduler_type == "lambda_lr":
        if "lr_lambda" not in scheduler_kwargs:
            raise ValueError("`scheduler_kwargs` must contain `lr_lambda` function for `lambda_lr` scheduler.")
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, **scheduler_kwargs)
    
    # Force disable AMP on incompatible devices
    if use_amp and not _is_amp_compatible(device):
        print(f"Warning: AMP requested but not compatible with {device}. Falling back to FP32.")
        use_amp = False
    
    # Create GradScaler for AMP if enabled and compatible
    scaler = None
    if use_amp:
        try:
            scaler = torch.amp.GradScaler(device)
        except Exception as e:
            print(f"Warning: Failed to create GradScaler for {device}: {e}. Falling back to FP32.")
            use_amp = False
    
    # Initialize tracking variables
    train_loss_history: List[float] = []
    val_loss_history: List[float] = []
    best_val_loss = float('inf')
    step_count = 0
    micro_idx = 0
    
    # Setup tqdm progress bar
    pbar = None
    is_map_style = not isinstance(train_loader.dataset, IterableDataset)
    if use_tqdm and is_map_style:
        # Adjust total for step limiting if applicable
        pbar_total = len(train_loader)
        if total_steps is not None:
            pbar_total = min(pbar_total, total_steps * accum_steps)
        pbar = tqdm_auto(desc="Training", leave=False, total=pbar_total)
    elif use_tqdm and not is_map_style and total_steps is not None:
        pbar = tqdm_auto(desc="Training", leave=False, total=total_steps * accum_steps)
    
    # Save initial checkpoint if needed
    if save_every_steps is not None and output_dir is not None:
        raw_model = model.module if hasattr(model, 'module') else model
        checkpointer.save_checkpoint(
            save_dir=os.path.join(output_dir, "checkpoints"),
            filename=f"step_-1.pt",
            metadata={"step": -1, "config": kwargs.get("config", {})},
            model=raw_model,
            optimizer=optimizer,
        )
    
    optimizer.zero_grad(set_to_none=True)
    
    try:
        should_break = False
        while not should_break:
            for batch in train_loader:
                if total_steps is not None and step_count >= total_steps:
                    should_break = True
                    break
                
                # Move batch to device
                batch = to_device(batch, device)
                
                # Forward pass with optional AMP
                if use_amp and scaler is not None:
                    with torch.amp.autocast(device):
                        loss = model(batch)
                    if accum_steps > 1:
                        loss = loss / float(accum_steps)
                    scaler.scale(loss).backward()
                else:
                    loss = model(batch)
                    if accum_steps > 1:
                        loss = loss / float(accum_steps)
                    loss.backward()
                
                micro_idx += 1
                
                # Optimization step with gradient accumulation
                if micro_idx % accum_steps == 0:
                    # Gradient clipping
                    if norm_clip_value is not None:
                        params = [p for p in model.parameters() if p.grad is not None]
                        if params:
                            if use_amp and scaler is not None:
                                scaler.unscale_(optimizer)
                            clip_grad_norm_(params, norm_clip_value, norm_type=2.0)
                    
                    # Optimizer step
                    if use_amp and scaler is not None:
                        scaler.step(optimizer)
                        scaler.update()
                    else:
                        optimizer.step()
                    
                    optimizer.zero_grad(set_to_none=True)
                    
                    # Learning rate scheduling
                    if scheduler is not None:
                        scheduler.step()
                    
                    step_count += 1
                    
                    # Loss tracking
                    if track_loss and (step_count % log_interval == 0):
                        # Reconstruct the actual loss (undo accumulation scaling)
                        actual_loss = loss * accum_steps if accum_steps > 1 else loss
                        train_loss_history.append(float(actual_loss.detach().cpu().item()))
                    
                    # Logging
                    if enable_logging:
                        actual_loss = loss * accum_steps if accum_steps > 1 else loss
                        logger.info("Training step", extra={"metrics": {"train_loss": actual_loss.item()}})
                    
                    # Validation
                    if val_loader is not None and step_count > 0 and step_count % val_interval == 0:
                        val_loss = _eval_loss(model, val_loader, device)
                        val_loss_history.append(val_loss)
                        
                        if enable_logging:
                            logger.info("Validation step", extra={"metrics": {"val_loss": val_loss}})
                        
                        # Save best model
                        if save_best_model:
                            if output_dir is None:
                                raise ValueError("output_dir must be provided when save_best_model is True.")
                            if val_loss < best_val_loss:
                                best_val_loss = val_loss
                                raw_model = model.module if hasattr(model, 'module') else model
                                checkpointer.save_checkpoint(
                                    save_dir=os.path.join(output_dir, "checkpoints"),
                                    filename="best_model.pt",
                                    metadata={"val_loss": best_val_loss, "step": step_count, "config": kwargs.get("config", {})},
                                    model=raw_model,
                                    optimizer=optimizer,
                                )
                    
                    # Save checkpoint over steps
                    if (save_every_steps is not None 
                        and output_dir is not None
                        and step_count > 0 
                        and step_count % save_every_steps == 0):
                        raw_model = model.module if hasattr(model, 'module') else model
                        checkpointer.save_checkpoint(
                            save_dir=os.path.join(output_dir, "checkpoints"),
                            filename=f"step_{step_count}.pt",
                            metadata={"step": step_count, "config": kwargs.get("config", {})},
                            model=raw_model,
                            optimizer=optimizer,
                        )
                
                # Update progress bar
                if pbar:
                    actual_loss = loss * accum_steps if accum_steps > 1 else loss
                    pbar.update(1)
                    pbar.set_postfix(loss=f"{actual_loss.item():.4f}")
            
            # For iterable-style datasets, we'll only do one pass if total_steps is not set
            if total_steps is None:
                should_break = True
        
        # Handle incomplete gradient accumulation at the end
        if micro_idx % accum_steps != 0:
            # Gradient clipping
            if norm_clip_value is not None:
                params = [p for p in model.parameters() if p.grad is not None]
                if params:
                    if use_amp and scaler is not None:
                        scaler.unscale_(optimizer)
                    clip_grad_norm_(params, norm_clip_value, norm_type=2.0)
            
            # Optimizer step
            if use_amp and scaler is not None:
                scaler.step(optimizer)
                scaler.update()
            else:
                optimizer.step()
            
            optimizer.zero_grad(set_to_none=True)
            
            # Learning rate scheduling
            if scheduler is not None:
                scheduler.step()
            
            step_count += 1
        
        # Final validation check
        if val_loader is not None and (step_count == 0 or step_count % val_interval != 0):
            final_val_loss = _eval_loss(model, val_loader, device)
            val_loss_history.append(final_val_loss)
            
            if enable_logging:
                logger.info("Final validation", extra={"metrics": {"val_loss": final_val_loss}})
            
            # Final best model check
            if save_best_model and output_dir is not None:
                if final_val_loss < best_val_loss:
                    best_val_loss = final_val_loss
                    raw_model = model.module if hasattr(model, 'module') else model
                    checkpointer.save_checkpoint(
                        save_dir=os.path.join(output_dir, "checkpoints"),
                        filename="best_model.pt",
                        metadata={"val_loss": best_val_loss, "step": step_count, "config": kwargs.get("config", {})},
                        model=raw_model,
                        optimizer=optimizer,
                    )
        
        # Final checkpoint save
        if (save_every_steps is not None
            and output_dir is not None 
            and step_count % save_every_steps != 0):
            raw_model = model.module if hasattr(model, 'module') else model
            checkpointer.save_checkpoint(
                save_dir=os.path.join(output_dir, "checkpoints"),
                filename=f"step_{step_count}.pt",
                metadata={"step": step_count, "config": kwargs.get("config", {})},
                model=raw_model,
                optimizer=optimizer,
            )
    
    finally:
        if pbar:
            pbar.close()
    
    # Build result dictionary
    result = {"model": model}
    
    if track_loss:
        result["train_loss_history"] = train_loss_history
    
    if val_loader is not None:
        result["val_loss_history"] = val_loss_history
    
    if save_best_model and best_val_loss < float('inf'):
        result['best_val_loss'] = best_val_loss
    
    return result