"""
LLM-compiled training loop combining atomic features: checkpoint_best_model, checkpoint_over_steps, grad_accum, grad_norm_clip, logging, loss_tracking, lr_scheduling, step_limiting, validation
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['checkpoint_best_model', 'checkpoint_over_steps', 'grad_accum', 'grad_norm_clip', 'logging', 'loss_tracking', 'lr_scheduling', 'step_limiting', 'validation']
__llm_compiled__ = True

from typing import Optional, Dict, Any, List
import os
import logging

import torch
import torch.nn as nn
from torch.nn.utils import clip_grad_norm_

import gpt_lab.checkpointer as checkpointer

logger = logging.getLogger(__name__)


@torch.no_grad()
def _eval_loss(model: nn.Module, loss_fn, loader) -> float:
    """Helper to compute validation loss."""
    was_training = model.training
    model.eval()
    total, count = 0.0, 0
    for batch in loader:
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total += float(loss.detach().cpu().item())
        count += 1
    if was_training:
        model.train()
    return total / max(count, 1)


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # gradient accumulation
    accum_steps: int = 1,
    # gradient norm clipping
    norm_clip_value: Optional[float] = None,
    # loss tracking
    track_loss: bool = False,
    log_interval: int = 1,
    # learning rate scheduling
    lr_scheduler_type: Optional[str] = None,
    scheduler_kwargs: Optional[Dict[str, Any]] = None,
    warmup_steps: int = 0,
    max_lr: Optional[float] = None,
    min_lr: float = 0.0,
    # step limiting
    total_steps: Optional[int] = None,
    # validation
    val_loader = None,
    val_interval: int = 10,
    # checkpoint_best_model
    save_best_model: bool = False,
    # checkpoint_over_steps
    save_every_steps: Optional[int] = None,
    output_dir: Optional[str] = None,
    # logging
    enable_logging: bool = False,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Combined training loop with multiple atomic features."""
    model.train()
    
    # Initialize variables
    train_loss_history: List[float] = []
    val_loss_history: List[float] = []
    best_val_loss = float('inf')
    
    # Gradient accumulation setup
    if accum_steps is None or accum_steps < 1:
        accum_steps = 1
    
    # Determine total steps if not provided for LR scheduling
    if lr_scheduler_type is not None and total_steps is None:
        try:
            total_steps = len(train_loader)
        except:
            total_steps = 1000  # fallback
    
    # Get current learning rate for max_lr if not specified
    if lr_scheduler_type is not None and max_lr is None:
        max_lr = optimizer.param_groups[0]['lr']
    
    # Create scheduler
    scheduler = None
    if lr_scheduler_type is not None:
        scheduler_kwargs = scheduler_kwargs or {}
        if lr_scheduler_type == "cosine":
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer, T_max=total_steps, eta_min=min_lr, **scheduler_kwargs
            )
        elif lr_scheduler_type == "linear":
            def lambda_lr(step):
                if step < warmup_steps:
                    return step / max(1, warmup_steps)
                progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
                return max(min_lr / max_lr, 1.0 - progress)
            scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lambda_lr, **scheduler_kwargs)
        elif lr_scheduler_type == "step":
            step_size = max(1, total_steps // 3)
            scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=0.1, **scheduler_kwargs)
        elif lr_scheduler_type == "exponential":
            gamma = (min_lr / max_lr) ** (1.0 / total_steps)
            scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=gamma, **scheduler_kwargs)
        elif lr_scheduler_type == "lambda_lr":
            if "lr_lambda" not in scheduler_kwargs:
                raise ValueError("`scheduler_kwargs` must contain `lr_lambda` function for `lambda_lr` scheduler.")
            scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, **scheduler_kwargs)
    
    # Save initial checkpoint if needed
    if save_every_steps is not None and output_dir is not None:
        raw_model = model.module if hasattr(model, 'module') else model
        checkpointer.save_checkpoint(
            save_dir=os.path.join(output_dir, "checkpoints"),
            filename=f"step_-1.pt",
            metadata={"step": -1, "config": kwargs.get("config", {})},
            model=raw_model,
            optimizer=optimizer,
        )
    
    # Training setup
    data_iter = iter(train_loader)
    step_count = 0
    micro_idx = 0
    optimizer.zero_grad(set_to_none=True)

    while True:
        if total_steps is not None and step_count >= total_steps:
            break

        try:
            batch = next(data_iter)
        except StopIteration:
            if total_steps is None:
                break
            data_iter = iter(train_loader)
            batch = next(data_iter)

        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)
        
        # Scale loss for gradient accumulation
        if accum_steps > 1:
            loss = loss / float(accum_steps)

        loss.backward()
        micro_idx += 1

        # Optimizer step with gradient accumulation
        if micro_idx % accum_steps == 0:
            # Apply gradient clipping
            if norm_clip_value is not None:
                params = [p for p in model.parameters() if p.grad is not None]
                if params:
                    clip_grad_norm_(params, norm_clip_value, norm_type=2.0)
            
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            step_count += 1
            
            # Step scheduler if it exists
            if scheduler is not None:
                scheduler.step()
            
            # Track loss if enabled
            if track_loss and (step_count % log_interval == 0):
                # Rescale loss back for logging
                original_loss = loss.item() * accum_steps if accum_steps > 1 else loss.item()
                train_loss_history.append(float(original_loss))
            
            # Logging
            if enable_logging:
                original_loss = loss.item() * accum_steps if accum_steps > 1 else loss.item()
                logger.info("Training step", extra={"metrics": {"train_loss": original_loss}})
            
            # Validation
            if val_loader is not None and step_count > 0 and step_count % val_interval == 0:
                val_loss = _eval_loss(model, loss_fn, val_loader)
                val_loss_history.append(val_loss)
                
                # Logging validation
                if enable_logging:
                    logger.info("Validation step", extra={"metrics": {"val_loss": val_loss}})
                
                # Check if this is the best model
                if save_best_model:
                    if output_dir is None:
                        raise ValueError("output_dir must be provided when save_best_model is True.")
                    
                    if val_loss < best_val_loss:
                        best_val_loss = val_loss
                        raw_model = model.module if hasattr(model, 'module') else model
                        checkpointer.save_checkpoint(
                            save_dir=os.path.join(output_dir, "checkpoints"),
                            filename="best_model.pt",
                            metadata={"val_loss": best_val_loss, "step": step_count, "config": kwargs.get("config", {})},
                            model=raw_model,
                            optimizer=optimizer,
                        )
            
            # Checkpoint saving
            if (save_every_steps is not None 
                and output_dir is not None
                and step_count > 0 
                and step_count % save_every_steps == 0):
                raw_model = model.module if hasattr(model, 'module') else model
                checkpointer.save_checkpoint(
                    save_dir=os.path.join(output_dir, "checkpoints"),
                    filename=f"step_{step_count}.pt",
                    metadata={"step": step_count, "config": kwargs.get("config", {})},
                    model=raw_model,
                    optimizer=optimizer,
                )

    # Handle incomplete accumulation window
    if micro_idx % accum_steps != 0:
        # Apply gradient clipping
        if norm_clip_value is not None:
            params = [p for p in model.parameters() if p.grad is not None]
            if params:
                clip_grad_norm_(params, norm_clip_value, norm_type=2.0)
        
        optimizer.step()
        step_count += 1
        
        # Step scheduler if it exists
        if scheduler is not None:
            scheduler.step()
    
    # Final validation at end of training
    if val_loader is not None and (step_count == 0 or step_count % val_interval != 0):
        final_val_loss = _eval_loss(model, loss_fn, val_loader)
        val_loss_history.append(final_val_loss)
        
        # Logging final validation
        if enable_logging:
            logger.info("Final validation", extra={"metrics": {"val_loss": final_val_loss}})
        
        # Check if final validation is the best
        if save_best_model and output_dir is not None:
            if final_val_loss < best_val_loss:
                best_val_loss = final_val_loss
                raw_model = model.module if hasattr(model, 'module') else model
                checkpointer.save_checkpoint(
                    save_dir=os.path.join(output_dir, "checkpoints"),
                    filename="best_model.pt",
                    metadata={"val_loss": best_val_loss, "step": step_count, "config": kwargs.get("config", {})},
                    model=raw_model,
                    optimizer=optimizer,
                )
    
    # Final checkpoint if needed
    if (save_every_steps is not None
        and output_dir is not None 
        and step_count % save_every_steps != 0):
        raw_model = model.module if hasattr(model, 'module') else model
        checkpointer.save_checkpoint(
            save_dir=os.path.join(output_dir, "checkpoints"),
            filename=f"step_{step_count}.pt",
            metadata={"step": step_count, "config": kwargs.get("config", {})},
            model=raw_model,
            optimizer=optimizer,
        )

    # Build result
    result = {"model": model}
    if track_loss:
        result["train_loss_history"] = train_loss_history
    if val_loader is not None:
        result["val_loss_history"] = val_loss_history
    if save_best_model and best_val_loss != float('inf'):
        result["best_val_loss"] = best_val_loss
    
    return result
