"""
LLM-compiled training loop combining atomic features: grad_accum, logging, multi_epoch, mixed_precision
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'logging', 'multi_epoch', 'mixed_precision']
__llm_compiled__ = True

import logging
from typing import Optional, Dict, Any

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)


def _is_amp_compatible(device_str: str) -> bool:
    """Check if device supports AMP properly."""
    if device_str.startswith('cuda'):
        return True
    elif device_str == 'mps':
        # MPS has issues with GradScaler in certain PyTorch versions
        return False
    return False


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # grad accum knobs
    accum_steps: int = 1,
    # logging
    enable_logging: bool = False,
    # multi-epoch knobs
    num_epochs: int = 1,
    # mixed precision knobs
    use_amp: Optional[bool] = False,
    loss_scale: Optional[float] = None,
    device: Optional[str] = None,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Combined training loop with gradient accumulation, logging, multi-epoch, and mixed precision."""
    model.train()
    
    if accum_steps is None or accum_steps < 1:
        accum_steps = 1
    
    # Infer device from model if not provided
    if device is None:
        device = str(next(model.parameters()).device)
    
    # Auto-detect AMP compatibility if not explicitly set
    if use_amp is None:
        use_amp = _is_amp_compatible(device)
    
    # Force disable AMP on incompatible devices
    if use_amp and not _is_amp_compatible(device):
        print(f"Warning: AMP requested but not compatible with {device}. Falling back to FP32.")
        use_amp = False
    
    # Create GradScaler for AMP if enabled and compatible
    scaler = None
    if use_amp:
        try:
            scaler = torch.amp.GradScaler(device)
        except Exception as e:
            print(f"Warning: Failed to create GradScaler for {device}: {e}. Falling back to FP32.")
            use_amp = False
    
    for epoch in range(num_epochs):
        micro_idx = 0
        optimizer.zero_grad(set_to_none=True)
        
        for batch in train_loader:
            xb, yb = batch
            
            if use_amp and scaler is not None:
                # Forward pass with autocast
                with torch.amp.autocast(device):
                    logits = model(xb)
                    loss = loss_fn(logits, yb)
            else:
                # Standard precision training
                logits = model(xb)
                loss = loss_fn(logits, yb)
            
            if enable_logging:
                logger.info("Training step", extra={"metrics": {"train_loss": loss.item()}})
            
            if accum_steps > 1:
                loss = loss / float(accum_steps)
            
            if use_amp and scaler is not None:
                # Backward pass with gradient scaling
                scaler.scale(loss).backward()
            else:
                loss.backward()
            
            micro_idx += 1
            
            if micro_idx % accum_steps == 0:
                if use_amp and scaler is not None:
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    optimizer.step()
                optimizer.zero_grad(set_to_none=True)
        
        # Handle case where last accumulation window is incomplete
        if micro_idx % accum_steps != 0:
            if use_amp and scaler is not None:
                scaler.step(optimizer)
                scaler.update()
            else:
                optimizer.step()
            optimizer.zero_grad(set_to_none=True)

    return {"model": model}