"""
LLM-compiled training loop combining atomic features: grad_accum, logging, multi_epoch
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'logging', 'multi_epoch']
__llm_compiled__ = True

import logging
from typing import Dict, Any

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # grad accum knobs
    accum_steps: int = 1,
    # logging
    enable_logging: bool = False,
    # multi-epoch knobs
    num_epochs: int = 1,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Training loop combining gradient accumulation, logging, and multi-epoch training."""
    model.train()

    if accum_steps is None or accum_steps < 1:
        accum_steps = 1

    for epoch in range(num_epochs):
        micro_idx = 0
        optimizer.zero_grad(set_to_none=True)

        for batch in train_loader:
            xb, yb = batch
            logits = model(xb)
            loss = loss_fn(logits, yb)

            if accum_steps > 1:
                loss = loss / float(accum_steps)

            if enable_logging:
                logger.info("Training step", extra={"metrics": {"train_loss": loss.item()}})

            loss.backward()
            micro_idx += 1

            if micro_idx % accum_steps == 0:
                optimizer.step()
                optimizer.zero_grad(set_to_none=True)

        # Handle case where last accumulation window is incomplete
        if micro_idx % accum_steps != 0:
            optimizer.step()

    return {"model": model}
