"""
LLM-compiled training loop combining atomic features: grad_accum, logging, multi_epoch, mixed_precision, weight_monitoring
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'logging', 'multi_epoch', 'mixed_precision', 'weight_monitoring']
__llm_compiled__ = True

import logging
from typing import Optional, Dict, Any, List

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)


def _is_amp_compatible(device_str: str) -> bool:
    """Check if device supports AMP properly."""
    if device_str.startswith('cuda'):
        return True
    elif device_str == 'mps':
        # MPS has issues with GradScaler in certain PyTorch versions
        return False
    return False


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # grad accum knobs
    accum_steps: int = 1,
    # logging
    enable_logging: bool = False,
    # multi-epoch knobs
    num_epochs: int = 1,
    # mixed precision knobs
    use_amp: Optional[bool] = False,
    loss_scale: Optional[float] = None,
    device: Optional[str] = None,
    # weight monitoring knobs
    track_weight_norms: bool = False,
    track_weight_changes: bool = False,
    weight_log_interval: int = 1,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Combined training loop with gradient accumulation, logging, multi-epoch, mixed precision, and weight monitoring."""
    model.train()
    
    # Grad accumulation setup
    if accum_steps is None or accum_steps < 1:
        accum_steps = 1
    
    # Mixed precision setup
    if device is None:
        device = str(next(model.parameters()).device)
    
    if use_amp is None:
        use_amp = _is_amp_compatible(device)
    
    if use_amp and not _is_amp_compatible(device):
        print(f"Warning: AMP requested but not compatible with {device}. Falling back to FP32.")
        use_amp = False
    
    scaler = None
    if use_amp:
        try:
            scaler = torch.amp.GradScaler(device)
        except Exception as e:
            print(f"Warning: Failed to create GradScaler for {device}: {e}. Falling back to FP32.")
            use_amp = False
    
    # Weight monitoring setup
    weight_norm_history: List[float] = []
    weight_change_history: List[float] = []
    step_count = 0
    
    initial_weights = {}
    if track_weight_changes:
        with torch.no_grad():
            for name, param in model.named_parameters():
                initial_weights[name] = param.data.clone()
    
    # Multi-epoch training
    for epoch in range(num_epochs):
        micro_idx = 0
        optimizer.zero_grad(set_to_none=True)
        
        for batch in train_loader:
            xb, yb = batch
            
            if use_amp and scaler is not None:
                # Forward pass with autocast
                with torch.amp.autocast(device):
                    logits = model(xb)
                    loss = loss_fn(logits, yb)
                
                if accum_steps > 1:
                    loss = loss / float(accum_steps)
                
                # Logging
                if enable_logging:
                    logger.info("Training step", extra={"metrics": {"train_loss": loss.item()}})
                
                # Backward pass with gradient scaling
                scaler.scale(loss).backward()
                micro_idx += 1
                
                if micro_idx % accum_steps == 0:
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)
            else:
                # Standard precision training
                logits = model(xb)
                loss = loss_fn(logits, yb)
                
                if accum_steps > 1:
                    loss = loss / float(accum_steps)
                
                # Logging
                if enable_logging:
                    logger.info("Training step", extra={"metrics": {"train_loss": loss.item()}})
                
                loss.backward()
                micro_idx += 1
                
                if micro_idx % accum_steps == 0:
                    optimizer.step()
                    optimizer.zero_grad(set_to_none=True)
            
            # Monitor weights if enabled
            if (track_weight_norms or track_weight_changes) and (step_count % weight_log_interval == 0):
                with torch.no_grad():
                    if track_weight_norms:
                        total_norm = 0.0
                        param_count = 0
                        for param in model.parameters():
                            if param.data is not None:
                                param_norm = param.data.norm()
                                total_norm += param_norm.item() ** 2
                                param_count += 1
                        
                        if param_count > 0:
                            total_norm = total_norm ** 0.5
                            weight_norm_history.append(total_norm)
                    
                    if track_weight_changes and initial_weights:
                        total_change = 0.0
                        param_count = 0
                        for name, param in model.named_parameters():
                            if name in initial_weights:
                                change = (param.data - initial_weights[name]).norm()
                                total_change += change.item() ** 2
                                param_count += 1
                        
                        if param_count > 0:
                            total_change = total_change ** 0.5
                            weight_change_history.append(total_change)
            
            step_count += 1
        
        # Handle incomplete accumulation window at end of epoch
        if micro_idx % accum_steps != 0:
            if use_amp and scaler is not None:
                scaler.step(optimizer)
                scaler.update()
            else:
                optimizer.step()
    
    # Prepare result - only include additional keys if features are enabled
    result = {"model": model}
    if use_amp:
        result["used_amp"] = use_amp
    if track_weight_norms and weight_norm_history:
        result["weight_norm_history"] = weight_norm_history
    if track_weight_changes and weight_change_history:
        result["weight_change_history"] = weight_change_history
    
    return result