"""
LLM-compiled training loop combining atomic features: grad_accum.py, early_stopping.py
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'early_stopping']
__llm_compiled__ = True

from typing import Optional, Dict, Any
import torch
import torch.nn as nn


@torch.no_grad()
def _eval_loss(model: nn.Module, loss_fn, loader) -> float:
    """Helper to compute validation loss."""
    was_training = model.training
    model.eval()
    total, count = 0.0, 0
    for batch in loader:
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total += float(loss.detach().cpu().item())
        count += 1
    if was_training:
        model.train()
    return total / max(count, 1)


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # grad accum knobs
    accum_steps: int = 1,
    # early stopping knobs
    val_loader = None,
    patience: int = 5,
    min_delta: float = 0.0,
    val_interval: int = 10,
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Training loop with gradient accumulation and early stopping."""
    model.train()

    if accum_steps is None or accum_steps < 1:
        accum_steps = 1

    micro_idx = 0
    optimizer.zero_grad(set_to_none=True)

    best_val_loss = float('inf')
    patience_counter = 0

    for batch_idx, batch in enumerate(train_loader):
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)

        if accum_steps > 1:
            loss = loss / float(accum_steps)

        loss.backward()
        micro_idx += 1

        if micro_idx % accum_steps == 0:
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)

        # Check for early stopping
        if val_loader is not None and batch_idx % val_interval == 0:
            val_loss = _eval_loss(model, loss_fn, val_loader)
            
            if val_loss < best_val_loss - min_delta:
                best_val_loss = val_loss
                patience_counter = 0
            else:
                patience_counter += 1
                
            if patience_counter >= patience:
                print(f"Early stopping at batch {batch_idx}")
                break

    # Handle case where last accumulation window is incomplete
    if micro_idx % accum_steps != 0:
        optimizer.step()

    return {"model": model}