"""
LLM-compiled training loop combining atomic features: grad_accum, loss_tracking
Generated by gpt-lab LLM compiler
Device: mps
"""

# Metadata for discovery and testing
__atomic_features__ = ['grad_accum', 'loss_tracking']
__llm_compiled__ = True

from typing import Optional, Dict, Any, List
import torch
import torch.nn as nn


def run_training(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    loss_fn,
    train_loader,
    *,
    # grad accum knobs
    accum_steps: int = 1,
    # loss tracking knobs
    track_loss: bool = False,
    log_interval: int = 1,  # track every batch by default
    # misc
    **kwargs,
) -> Dict[str, Any]:
    """Training loop with gradient accumulation and loss tracking."""
    model.train()
    
    if accum_steps is None or accum_steps < 1:
        accum_steps = 1

    train_loss_history: List[float] = []
    
    micro_idx = 0
    optimizer.zero_grad(set_to_none=True)

    for batch_idx, batch in enumerate(train_loader):
        xb, yb = batch
        logits = model(xb)
        loss = loss_fn(logits, yb)

        if accum_steps > 1:
            loss = loss / float(accum_steps)

        loss.backward()
        micro_idx += 1

        # Track loss if enabled
        if track_loss and (batch_idx % log_interval == 0):
            train_loss_history.append(float(loss.detach().cpu().item()) * accum_steps)

        if micro_idx % accum_steps == 0:
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)

    # Handle case where last accumulation window is incomplete
    if micro_idx % accum_steps != 0:
        optimizer.step()

    result = {"model": model}
    if track_loss:
        result["train_loss_history"] = train_loss_history
    
    return result